#!/bin/bash
/bin/mkdir -m 0755 -p ROOT_PKGROOTMODULEROOT
cat > ROOT_PKGROOTMODULEROOT/VERSION <<END
#%Module1.0
module-whatis "fftw"
module-whatis "Version: VERSION"
module-whatis "Description: fftw"
module-whatis "Compiler: ROLLCOMPILER"
if {! [info exists ::env(MPIHOME)]} {
  puts stderr "Need to load an mpi module before loading fftw_VERSION"
  exit 1
}
foreach {x} [glob -directory /opt/fftw/VERSION/ROLLCOMPILER -tails *] {
  if {[regexp \$x \$::env(MPIHOME)]} {
    set mpi \$x
    break
  }
}
if {! [info exists mpi]} {
  if {[ regexp ScaleMP \$::env(MPIHOME)]} {
      set mpi vsmp
  }
}
if {! [info exists mpi]} {
  puts stderr "No supported MPI flavor found"
  exit 1
}
foreach {x} [glob -directory /opt/fftw/VERSION/ROLLCOMPILER/\$mpi -tails *] {
  if {[regexp \$x \$::env(MPIHOME)]} {
    set network \$x
    break
  }
}
if {! [info exists network]} {
  if {[ regexp ScaleMP \$::env(MPIHOME)]} {
      set network ib
  }
}
if {! [info exists network]} {
  puts stderr "No supported network found"
  exit 1
}
set fftwHome /opt/fftw/VERSION/ROLLCOMPILER/\$mpi/\$network
setenv FFTWHOME \$fftwHome
prepend-path PATH \$fftwHome/bin
prepend-path LD_LIBRARY_PATH \$fftwHome/lib
prepend-path LIBPATH \$fftwHome/lib
END

chmod 0644  ROOT_PKGROOTMODULEROOT/VERSION

cat > ROOT_PKGROOTMODULEROOT/.version.VERSION <<END
#%Module1.0
set ModulesVersion "VERSION"
END

(cd ROOT_PKGROOTMODULEROOT; /bin/ln -s .version.VERSION .version )

