#%Module1.0
module-whatis "fftw"
module-whatis "Version: VERSION"
module-whatis "Description: fftw"
module-whatis "Compiler: COMPILERNAME"
module-whatis "MPI Flavors: ROLLMPI"
# Look for MPI flavor in LOADEDMODULES. If no MPI module is loaded, default to
# first element in ROLLMPI.
set mpi [lindex [split "ROLLMPI" "/ "] 0]
foreach {module} [split $::env(LOADEDMODULES) :] {
  set module [lindex [split $module /] 0]
  if {[regexp [format {%s(/|\s|$)} $module] "ROLLMPI"]} {
    set mpi $module
  }
}
set fftwHome /opt/fftw/VERSION/COMPILERNAME/$mpi
setenv FFTWHOME $fftwHome
prepend-path PATH $fftwHome/bin
prepend-path LD_LIBRARY_PATH $fftwHome/lib
prepend-path LIBPATH $fftwHome/lib
