#%Module1.0
module-whatis "fftw"
module-whatis "Version: VERSION"
module-whatis "Description: fftw"
module-whatis "Compiler: COMPILERNAME"
module-whatis "MPI Flavors: ROLLMPI"
if {! [info exists ::env(MPIHOME)] || ! [info exists ::env(LOADEDMODULES)]} {
  puts stderr "Need to load an mpi module before loading fftw/VERSION"
  exit 1
}
foreach {x} [list ROLLMPI] {
  # Look for flavor in LOADEDMODULES, delimited by colon or end of string.
  # Can also be followed by / (version number).
  if {[regexp [format {[:^]%s[:/$]} $x] $::env(LOADEDMODULES)]} {
    set mpi $x
    break
  }
}
if {! [info exists mpi]} {
  puts stderr "No supported MPI flavor found"
  exit 1
}
set fftwHome /opt/fftw/VERSION/COMPILERNAME/$mpi
setenv FFTWHOME $fftwHome
prepend-path PATH $fftwHome/bin
prepend-path LD_LIBRARY_PATH $fftwHome/lib
prepend-path LIBPATH $fftwHome/lib
